/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.scripts.JO;

/**
 *
 * @author gabii
 */
public class ViewImc extends javax.swing.JFrame {

    /**
     * Creates new form ViewImc
     */
    public ViewImc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jl_peso = new javax.swing.JLabel();
        jl_estatura = new javax.swing.JLabel();
        jtf_peso = new javax.swing.JTextField();
        jtf_estatura = new javax.swing.JTextField();
        jb_limpiar = new javax.swing.JButton();
        jb_calcular = new javax.swing.JButton();
        jcb_sexo = new javax.swing.JComboBox<>();
        jl_titulo = new javax.swing.JLabel();
        jl_txt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jl_peso.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jl_peso.setText("Peso:");

        jl_estatura.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jl_estatura.setText("Estatura:");

        jtf_peso.setBackground(new java.awt.Color(204, 204, 204));
        jtf_peso.setText("0.0");
        jtf_peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_pesoActionPerformed(evt);
            }
        });
        jtf_peso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_pesoKeyTyped(evt);
            }
        });

        jtf_estatura.setBackground(new java.awt.Color(204, 204, 204));
        jtf_estatura.setText("0.0");
        jtf_estatura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_estaturaKeyTyped(evt);
            }
        });

        jb_limpiar.setBackground(new java.awt.Color(0, 0, 0));
        jb_limpiar.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jb_limpiar.setForeground(new java.awt.Color(255, 255, 255));
        jb_limpiar.setText("Limpiar");
        jb_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_limpiarActionPerformed(evt);
            }
        });

        jb_calcular.setBackground(new java.awt.Color(0, 0, 0));
        jb_calcular.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jb_calcular.setForeground(new java.awt.Color(255, 255, 255));
        jb_calcular.setText("Calcular");
        jb_calcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_calcularMouseClicked(evt);
            }
        });
        jb_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_calcularActionPerformed(evt);
            }
        });

        jcb_sexo.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jcb_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mujeres", "Hombres" }));
        jcb_sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_sexoActionPerformed(evt);
            }
        });

        jl_titulo.setFont(new java.awt.Font("Cooper Black", 2, 14)); // NOI18N
        jl_titulo.setText("Calcular IMC");

        jl_txt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jl_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_estatura)
                            .addComponent(jl_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_estatura, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jb_calcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(jb_limpiar)
                        .addGap(83, 83, 83))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jl_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_estatura, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_estatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jl_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_calcular)
                    .addComponent(jb_limpiar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_pesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_pesoActionPerformed

    private void jtf_pesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_pesoKeyTyped
        char c=evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "No puedes ingresar letras");
        }
    }//GEN-LAST:event_jtf_pesoKeyTyped

    private void jtf_estaturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_estaturaKeyTyped
        char c=evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "No puedes ingresar letras");
        }

    }//GEN-LAST:event_jtf_estaturaKeyTyped

    private void jb_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_limpiarActionPerformed
        this.jtf_peso.setText("0.0");
        this.jtf_estatura.setText("0.0");
    }//GEN-LAST:event_jb_limpiarActionPerformed

    private void jb_calcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_calcularMouseClicked
        try {
            float peso = 0.0f;
            float estatura = 0.0f;
            float imc = 0.0f;
            peso = Float.parseFloat(this.jtf_peso.getText());
            estatura = Float.parseFloat(this.jtf_estatura.getText());
            if(estatura>2){
                estatura = Float.parseFloat(JOptionPane.showInputDialog("Ingrese Solo  Números Decimales!"));
                this.jtf_estatura.setText(String.valueOf(estatura));
            }
            else{
                imc = peso / (estatura * estatura);

                int operacion = jcb_sexo.getSelectedIndex();
                if (operacion == 0)
                {
                    jb_calcular.setText(String.valueOf("Mujer"));
                }
                else if (imc < 18.5) {
                    JOptionPane.showMessageDialog(this, "IMC: "+imc+    "Lo Siento, Tu Peso Es Muy Bajo!");
                } else if (imc > 18.5 && imc <= 24.9) {
                    JOptionPane.showMessageDialog(this, "IMC: "+imc+    "Perfecto, Su Peso Es Normal");
                } else if (imc > 25 && imc <= 29.9) {
                    JOptionPane.showMessageDialog(this, "IMC: "+imc+    "Oye, Tienes Sobrepeso ");
                } else if (imc > 30 && imc <= 34.9) {
                    JOptionPane.showMessageDialog(this, "IMC: "+imc+    "Cuida Tu Alimentaciòn, ¡Tienes Obesidad!");
                }
            }
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "¡Solo Ingrese Números, Porfavor!");
        }
        try {
            float peso = 0.0f;
            float estatura = 0.0f;
            float imc = 0.0f;
            peso = Float.parseFloat(this.jtf_peso.getText());
            estatura = Float.parseFloat(this.jtf_estatura.getText());
            if(estatura>2){
                estatura = Float.parseFloat(JOptionPane.showInputDialog("Ingrese Solo  Números Decimales!"));
                this.jtf_estatura.setText(String.valueOf(estatura));
            }
            else{
                imc = peso / (estatura * estatura);

                int operacion = jcb_sexo.getSelectedIndex();
                if (operacion == 1)
                {
                    jb_calcular.setText(String.valueOf("Hombre"));
                }
                else if (imc < 20) {
                    JOptionPane.showMessageDialog(this, "IMC: "+imc+    "Lo Siento, Estas Bajo De Peso!");
                } else if (imc > 20 && imc <= 25) {
                    JOptionPane.showMessageDialog(this, "IMC: "+imc+    "Muy Bien, Tu Peso Es Normal");
                } else if (imc > 26 && imc <= 29) {
                    JOptionPane.showMessageDialog(this, "IMC: "+imc+    "¡Tienes Sobrepeso!");
                } else if (imc > 30) {
                    JOptionPane.showMessageDialog(this, "IMC: "+imc+    "Cuida Tu Alimentaciòn, ¡Tienes Obesidad!");
                }
            }
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "¡Solo Ingrese Números, Porfavor!");
        }
    }//GEN-LAST:event_jb_calcularMouseClicked

    private void jb_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_calcularActionPerformed

    }//GEN-LAST:event_jb_calcularActionPerformed

    private void jcb_sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_sexoActionPerformed

    }//GEN-LAST:event_jcb_sexoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewImc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewImc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewImc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewImc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewImc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel jPanel1;
    public javax.swing.JButton jb_calcular;
    public javax.swing.JButton jb_limpiar;
    public javax.swing.JComboBox<String> jcb_sexo;
    public javax.swing.JLabel jl_estatura;
    public javax.swing.JLabel jl_peso;
    public javax.swing.JLabel jl_titulo;
    public javax.swing.JLabel jl_txt;
    public javax.swing.JTextField jtf_estatura;
    public javax.swing.JTextField jtf_peso;
    // End of variables declaration//GEN-END:variables
}
